//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaoTaoShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> sum_price { get; set; }
        public Nullable<int> shop_id { get; set; }
        public string title { get; set; }
    
        public virtual order order { get; set; }
        public virtual shopping shopping { get; set; }
    }
}
