//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaoTaoShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shopping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shopping()
        {
            this.comment = new HashSet<comment>();
            this.order_detail = new HashSet<order_detail>();
            this.shop_car = new HashSet<shop_car>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> cid { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> sale_price { get; set; }
        public int number { get; set; }
        public string detail { get; set; }
        public string img { get; set; }
        public string shop_number { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_detail> order_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shop_car> shop_car { get; set; }
    }
}
