//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaoTaoShopping.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaoTaoProjectDBEntities : DbContext
    {
        public TaoTaoProjectDBEntities()
            : base("name=TaoTaoProjectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<shopping> shopping { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<order_detail> order_detail { get; set; }
        public virtual DbSet<address> address { get; set; }
        public virtual DbSet<shop_car> shop_car { get; set; }
    }
}
